import type { Metadata } from "next";
import "./globals.css";
import { DragDropProvider } from "./components/drag-drop-context";

export const metadata: Metadata = {
  title: "Create Next Todos App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DragDropProvider>
        <body className={`font-sarabun min-h-screen`}>{children}</body>
      </DragDropProvider>
    </html>
  );
}
